name: Fetch new content of tracked links to files

on:
  schedule:
    - cron: '* * * * * '
  push:
    branches:
      - main

jobs:
  make_tracked_links_file:
    name: Make files tree
    runs-on: macos-10.15

    steps:

      - name: Clone.
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies.
        run: |
          pip install -r requirements.txt

      - name: Generate files tree.
        env:
          OUTPUT_FOLDER: "data_ci/"
        run: |
          git pull
          python make_files_tree.py

      - name: Commit and push changes.
        run: |
          git checkout data

          rm -rf data
          mv data_ci data

          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

          git add .
          git commit -m "Update content of files"
          git push
