name: Fetch new content of tracked links and files

on:
  schedule:
    - cron: '* * * * *'
  push:
    # trigger on updated linkbase
    branches:
      - main

jobs:
  fetch_new_content:
    name: Make files tree
    runs-on: macos-10.15
    timeout-minutes: 10

    steps:

      - name: Clone.
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies.
        run: |
          pip install -r requirements.txt

      - name: Generate files tree.
        env:
          OUTPUT_FOLDER: "data_ci/"
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          TELEGRAM_SESSION_TEST: ${{ secrets.TELEGRAM_SESSION_TEST }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        run: |
          git pull
          python make_files_tree.py
          rm -rf __pycache__

      - name: Commit and push changes.
        run: |
          git checkout data

          rm -rf data
          mv data_ci data

          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

          git add .
          git commit -m "Update content of files"
          git push
