name: Fetch new content of tracked links and files

on:
  schedule:
    - cron: '* * 5 * *'
  push:
    # trigger on updated linkbase
    branches:
      - main

jobs:
  fetch_new_content:
    name: Make files tree
    runs-on: macos-10.15
    continue-on-error: true
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        mode: [
          "0",
          "6"
        ]

    steps:

      - name: Clone.
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies.
        run: |
          pip install -r requirements.txt

      - name: Generate files tree.
        env:
          OUTPUT_FOLDER: "data_ci/"
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          TELEGRAM_SESSION_TEST: ${{ secrets.TELEGRAM_SESSION_TEST }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          MODE: ${{ matrix.mode }}
        run: |
          git pull
          python make_files_tree.py
          rm -rf __pycache__

      - name: Prepare data for mode 0.
        if: matrix.mode == '0'
        run: |
          git checkout data

          mv data/web_res data_ci/web_res
          rm -rf data
          mv data_ci data

      - name: Prepare data for mode 6.
        if: matrix.mode == '6'
        run: |
          git checkout data

          mv data/web data_ci/web
          mv data/client data_ci/client
          mv data/server data_ci/server

          rm -rf data
          mv data_ci data

      - name: Commit and push changes.
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

          git add .
          git commit -m "Update content of files"
          git push
