name: Generate or update list of tracked links

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  make_tracked_links_file:
    name: Make tracked links file
    runs-on: macos-10.15

    steps:

      - name: Clone.
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
          submodules: recursive

      - name: Setup Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies.
        run: |
          pip install -r requirements.txt

      - name: Generate/update file with links.
        env:
          OUTPUT_FILENAME: "tracked_links_ci.txt"
        run: |
          python make_tracked_links_list.py

      - name: Commit and push changes.
        run: |
          git pull

          mv tracked_links_ci.txt tracked_links.txt

          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

          git add .
          git commit -m "Update tracked links"
          git push
